version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: Mansour is testing
          command: |
            echo "hello mans"
      -run : 
          name: testing another script
          command: | 
              cd reactnd-contacts-complete && npm install
      - run :
           name : tesing some thing again
           command : | 
                echo "MAnsour is echooooooooo"
      - run: 
          name: runing server 
          command : | 
              npm innstall && npm run server 
